hospital: healthcenterserver doctor patient1 patient2
healthcenterserver: healthcenterserver.c
	gcc  healthcenterserver.c -o healthcenterserver -lsocket -lnsl -lresolv
doctor: doctor.c
	gcc  doctor.c -o doctor -lsocket -lnsl -lresolv
patient1: patient1.c
	gcc  patient1.c -o patient1 -lsocket -lnsl -lresolv
patient2: patient2.c
	gcc  patient2.c -o patient2 -lsocket -lnsl -lresolv
